const countryFlagMap = {
  'United Kingdom': ':flag_gb:',
  'United States of America': ':flag_us:',
  Mexico: ':flag_mx:',
  Colombia: ':flag_co:',
  Peru: ':flag_pe:',
  Brazil: ':flag_br:',
  Chile: ':flag_cl:',
  Argentina: ':flag_ar:',
  Ireland: ':flag_ie:',
  France: ':flag_fr:',
  Portugal: ':flag_pt:',
  Spain: ':flag_es:',
  Germany: ':flag_de:',
  Sweden: ':flag_se:',
  Italy: ':flag_it:',
  Poland: ':flag_pl:',
  Lithuania: ':flag_lt:',
  Slovenia: ':flag_si:',
  Croatia: ':flag_hr:',
  'Bosnia and Herzegovina': ':flag_ba:',
  Serbia: ':flag_rs:',
  'North Macedonia': ':flag_mk:',
  Albania: ':flag_al:',
  Greece: ':flag_gr:',
  Hungary: ':flag_hu:',
  Romania: ':flag_ro:',
  Bulgaria: ':flag_bg:',
  Turkey: ':flag_tr:',
  Ukraine: ':flag_ua:',
  Russia: ':flag_ru:',
  Georgia: ':flag_ge:',
  Israel: ':flag_il:',
  Egypt: ':flag_eg:',
  'South Africa': ':flag_za:',
  Iraq: ':flag_iq:',
  'Saudi Arabia': ':flag_sa:',
  Iran: ':flag_ir:',
  Pakistan: ':flag_pk:',
  India: ':flag_in:',
  China: ':flag_cn:',
  Japan: ':flag_jp:',
  'South Korea': ':flag_kr:',
  Indonesia: ':flag_id:',
  Australia: ':flag_au:',
  Philippines: ':flag_ph:',
};

module.exports = countryFlagMap;
